# Site Settings
title:              Atekihcan
author:             Atekihcan
email:              com.atekihcan@gmail.com
description:        "A blog about Algorithms, Python, Image Processing, Pattern Recognition and Machine Learning, and a little bit of Android."
keywords:           "atekihcan, python, jekyll, algorithms, machine learning, pattern recognition"
logo_location:      "/assets/img/profile.png"
favicon:            "/assets/img/favicon.png"

# Handling Reading
exclude:            ['README.md', 'LICENSE.md']

# Conversion
markdown:           kramdown
kramdown:
    input:          GFM
highlighter:        pygments

# Serving
#url:                "http://atekihcan.github.io"
#baseurl:            ""

# Outputting
permalink:          /:title/

# Google Analytics
google_analytics_id: "UA-57470252-1 "